//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalamanderWnmp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalamanderWnmp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于作者 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加连接 的本地化字符串。
        /// </summary>
        public static string AddConn {
            get {
                return ResourceManager.GetString("AddConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wnmp 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调色 的本地化字符串。
        /// </summary>
        public static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编程面板 的本地化字符串。
        /// </summary>
        public static string CodePanel {
            get {
                return ResourceManager.GetString("CodePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常见问题 的本地化字符串。
        /// </summary>
        public static string CommonQuestions {
            get {
                return ResourceManager.GetString("CommonQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #16a085 的本地化字符串。
        /// </summary>
        public static string DefaultThemeColor {
            get {
                return ResourceManager.GetString("DefaultThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Http请求器 的本地化字符串。
        /// </summary>
        public static string HttpRequester {
            get {
                return ResourceManager.GetString("HttpRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主目录 的本地化字符串。
        /// </summary>
        public static string MainDir {
            get {
                return ResourceManager.GetString("MainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口扫描器 的本地化字符串。
        /// </summary>
        public static string PortScaner {
            get {
                return ResourceManager.GetString("PortScaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redis面板 的本地化字符串。
        /// </summary>
        public static string RedisPanel {
            get {
                return ResourceManager.GetString("RedisPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
